
--use master;
--CREATE DATABASE CJA_MyBase;


USE CJA_MyBase;
--DROP DATABASE CJA_MyBase;

CREATE TABLE TRAINING
(
	[IdTreining] INT PRIMARY KEY IDENTITY,
	[Treining] NVARCHAR(20) UNIQUE NOT NULL,
	[Information] NVARCHAR(100) NOT NULL
)

CREATE TABLE EXCERCISE
(
	[IdExcercise] INT PRIMARY KEY IDENTITY,
	[IdTraining] INT,
	[Excercise] NVARCHAR(20) NOT NULL,
	[Repeat] NVARCHAR(20) NOT NULL
	CONSTRAINT FK_EXCERCISE_TO_TREINING FOREIGN KEY ([IdTraining]) REFERENCES TRAINING([IdTreining]),
)

SELECT * FROM TRAINING;
SELECT * FROM EXCERCISE;


SELECT EXCERCISE.IdExcercise, EXCERCISE.IdTraining, EXCERCISE.Excercise, EXCERCISE.Repeat
	FROM EXCERCISE JOIN TRAINING
	ON EXCERCISE.IdTraining = TRAINING.IdTreining
	WHERE TRAINING.Treining = 'Ноги';

--DROP TABLE EXCERCISE;
--DROP TABLE TRAINING;

CREATE TABLE USERS
(
	[IdUser] INT PRIMARY KEY IDENTITY,
	[Login] NVARCHAR(20) NOT NULL,
	[Password] NVARCHAR(200) NOT NULL,
	[Height] INT NULL,
	[Width] INT NULL,
	[Information] NVARCHAR(MAX) NULL,
	[ImageDate] NVARCHAR(200) NULL
)

CREATE TABLE REPORT
(
	[IdReport] INT PRIMARY KEY IDENTITY,
	[IdUser] INT,
	[NameTraining] NVARCHAR(30),
	[DateTreining] NVARCHAR(30)
	CONSTRAINT FK_REPORT_TO_USERS FOREIGN KEY ([IdUser]) REFERENCES USERS([IdUser])
)

SELECT * FROM REPORT;
--DROP TABLE REPORT;

--сделать напоминания
CREATE TABLE REMINDER
(
	[IdReminder] INT PRIMARY KEY IDENTITY,
	[IdUser] INT,
	[DayTreining] NVARCHAR(30) NOT NULL,
	[TimeTreining] NVARCHAR(30) NOT NULL
	CONSTRAINT FK_REMINDER_TO_USERS FOREIGN KEY ([IdUser]) REFERENCES USERS([IdUser])
)

SELECT * FROM USERS;
SELECT * FROM REMINDER;
--DROP TABLE REMINDER;

UPDATE USERS
SET Height = 186, Width = 76
WHERE IdUser = 1;